# Credit Risk Analysis by using Machine Learning

## Checking for  Overfitting

#### Muhammad Nadeem
C00221923@itcarlow.ie

## Overfitting

- Overfitting is the problem of learning data by heart and cannot generally be accomplished through proper predictions of data samples that are not seen during the preparation.

# Libraries

In [1]:
# Import our libraries we are going to use for our data analysis.
import os,csv,io,zipfile,requests
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt


# Plotly visualizations
from plotly import tools
import plotly.plotly as py
import plotly.figure_factory as ff
import plotly.graph_objs as go
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
init_notebook_mode(connected=True)
from sklearn.linear_model import LinearRegression
model = LinearRegression()
from sklearn import metrics
from sklearn.cross_validation import train_test_split
from sklearn.cross_validation import cross_val_score
# predict bad loan if the predicted probability is greater than 0.2
from sklearn.preprocessing import binarize
from sklearn.neighbors import KNeighborsClassifier
from sklearn import cross_validation
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
#Import Xgboost

# For mysql connection
import mysql.connector as sql

# File system manangement
import os

# Deletion  of warning
import warnings
warnings.filterwarnings('ignore')

% matplotlib inline

C:\Users\mrferozi\Anaconda3\lib\site-packages\sklearn\cross_validation.py:44: DeprecationWarning:

This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.



# Reading Data Files

In [2]:
# List files in folder
print(os.listdir("C:/Users/mrferozi/Desktop/Thesis 2019/Dataset/home-credit-default-risk"))

['application_test-t1.dif', 'application_test-t1.txt', 'application_test.csv', 'application_test1.csv', 'application_train.csv', 'application_train1.csv', 'bureau.csv', 'bureau_balance.csv', 'credit_card_balance.csv', 'home1.csv', 'HomeCredit_columns_description.csv', 'Home_final.csv', 'installments_payments.csv', 'POS_CASH_balance.csv', 'previous_application.csv', 'sample_submission.csv', 'test.sql', 'train2.csv']


# Home credit default risk Dataset
References:* From the German Credit Risk Analysis : A Gentle Introduction: [ A Gentle Introduction ](https://www.kaggle.com/willkoehrsen/start-here-a-gentle-introduction)*

In [3]:
# Display Training data
df1 = pd.read_csv('C:/Users/mrferozi/Desktop/Thesis 2019/Dataset/home-credit-default-risk/application_train.csv')
print('Shape of the Traning dataset: ', df1.shape)
df1.head()

Shape of the Traning dataset:  (307511, 122)


SK_ID_CURR  TARGET NAME_CONTRACT_TYPE CODE_GENDER FLAG_OWN_CAR  \
0      100002       1         Cash loans           M            N   
1      100003       0         Cash loans           F            N   
2      100004       0    Revolving loans           M            Y   
3      100006       0         Cash loans           F            N   
4      100007       0         Cash loans           M            N   

  FLAG_OWN_REALTY  CNT_CHILDREN  AMT_INCOME_TOTAL  AMT_CREDIT  AMT_ANNUITY  \
0               Y             0          202500.0    406597.5      24700.5   
1               N             0          270000.0   1293502.5      35698.5   
2               Y             0           67500.0    135000.0       6750.0   
3               Y             0          135000.0    312682.5      29686.5   
4               Y             0          121500.0    513000.0      21865.5   

              ...              FLAG_DOCUMENT_18 FLAG_DOCUMENT_19  \
0             ...                             0                0   
1             ...                             0                0   
2             ...                             0                0   
3             ...                             0                0   
4             ...                             0                0   

  FLAG_DOCUMENT_20 FLAG_DOCUMENT_21 AMT_REQ_CREDIT_BUREAU_HOUR  \
0                0                0                        0.0   
1                0                0                        0.0   
2                0                0                        0.0   
3                0                0                        NaN   
4                0                0                        0.0   

  AMT_REQ_CREDIT_BUREAU_DAY  AMT_REQ_CREDIT_BUREAU_WEEK  \
0                       0.0                         0.0   
1                       0.0                         0.0   
2                       0.0                         0.0   
3                       NaN                         NaN   
4                       0.0                         0.0   

   AMT_REQ_CREDIT_BUREAU_MON  AMT_REQ_CREDIT_BUREAU_QRT  \
0                        0.0                        0.0   
1                        0.0                        0.0   
2                        0.0                        0.0   
3                        NaN                        NaN   
4                        0.0                        0.0   

   AMT_REQ_CREDIT_BUREAU_YEAR  
0                         1.0  
1                         0.0  
2                         0.0  
3                         NaN  
4                         0.0  

[5 rows x 122 columns]

Training dataset consist of 307511 Tuples and 122 observations

In [4]:
# remove multiple rows at once (axis=0 refers to rows)
df1.drop(df1.columns[30:122],axis=1, inplace=True)

In [5]:
print('Shape of the Traning dataset: ', df1.shape)

Shape of the Traning dataset:  (307511, 30)


In [6]:
df1.dtypes

SK_ID_CURR                      int64
TARGET                          int64
NAME_CONTRACT_TYPE             object
CODE_GENDER                    object
FLAG_OWN_CAR                   object
FLAG_OWN_REALTY                object
CNT_CHILDREN                    int64
AMT_INCOME_TOTAL              float64
AMT_CREDIT                    float64
AMT_ANNUITY                   float64
AMT_GOODS_PRICE               float64
NAME_TYPE_SUITE                object
NAME_INCOME_TYPE               object
NAME_EDUCATION_TYPE            object
NAME_FAMILY_STATUS             object
NAME_HOUSING_TYPE              object
REGION_POPULATION_RELATIVE    float64
DAYS_BIRTH                      int64
DAYS_EMPLOYED                   int64
DAYS_REGISTRATION             float64
DAYS_ID_PUBLISH                 int64
OWN_CAR_AGE                   float64
FLAG_MOBIL                      int64
FLAG_EMP_PHONE                  int64
FLAG_WORK_PHONE                 int64
FLAG_CONT_MOBILE                int64
FLAG_PHONE  

In [7]:
#create a new data frame
cols = ['TARGET','Gender','Credit_amount','Education','DAYS_BIRTH','Martial_status']
df4 = pd.DataFrame(columns=cols)
df4['Gender']=df1['CODE_GENDER']
df4['DAYS_BIRTH']=df1['DAYS_BIRTH']
df4['Martial_status']=df1['NAME_FAMILY_STATUS']
df4['Education']=df1['NAME_EDUCATION_TYPE']
df4['Credit_amount']=df1['AMT_CREDIT'].astype(int)
df4['TARGET']=df1['TARGET'].astype(int)
df4.shape

(307511, 6)

In [8]:
df4.isnull().sum()

TARGET            0
Gender            0
Credit_amount     0
Education         0
DAYS_BIRTH        0
Martial_status    0
dtype: int64

In [9]:
df4['Age'] = (df1['DAYS_BIRTH'] / 365)* -1
df4['Age']=df4["Age"].astype(float)
df4['Age']=df4["Age"].astype(int)
df4.shape

(307511, 7)

In [10]:
#DAYS_BIRTH
# remove a single column (axis=1 refers to columns)
df4.drop('DAYS_BIRTH', axis=1, inplace=True)

In [11]:
df4.Gender.replace('M',1,inplace=True)
df4.Gender.replace('F',0,inplace=True)

In [12]:
df4.Education.unique()

array(['Secondary / secondary special', 'Higher education',
       'Incomplete higher', 'Lower secondary', 'Academic degree'], dtype=object)

In [13]:
df4.Education.replace('Academic degree',1,inplace=True)

In [14]:
df4.Education.replace('Higher education',2,inplace=True)

In [15]:
df4.Education.replace('Incomplete higher',3,inplace=True)
df4.Education.replace('Secondary / secondary special',4,inplace=True)
df4.Education.replace('Lower secondary',5,inplace=True)

In [16]:
df4.Martial_status.unique()

array(['Single / not married', 'Married', 'Civil marriage', 'Widow',
       'Separated', 'Unknown'], dtype=object)

In [17]:
df4.Martial_status.replace('Single / not married',1,inplace=True)
df4.Martial_status.replace('Civil marriage',2,inplace=True)
df4.Martial_status.replace('Married',3,inplace=True)
df4.Martial_status.replace('Widow',4,inplace=True)
df4.Martial_status.replace('Separated',5,inplace=True)
df4.Martial_status.replace('Unknown',6,inplace=True)

In [18]:
df4.head()

TARGET Gender  Credit_amount  Education  Martial_status  Age
0       1      1         406597          4               1   25
1       0      0        1293502          2               3   45
2       0      1         135000          4               1   52
3       0      0         312682          4               2   52
4       0      1         513000          4               1   54

In [19]:
p=df4['TARGET'].value_counts()
print ('The loan paid on time by 0')
print ('The loan not paid on time by 1')
print ('-------------------------------',)
print (p)

The loan paid on time by 0
The loan not paid on time by 1
-------------------------------
0    282686
1     24825
Name: TARGET, dtype: int64


In [20]:
df4.shape

(307511, 6)

In [21]:
df4.to_csv(('C:\\Users\\mrferozi\\Desktop\\Thesis 2019\\Dataset\\home-credit-default-risk\\Home_final.csv'),index=False);

In [37]:
#importing data from database
db_connection = sql.connect(host='localhost', database='credit', user='root', password='none')
db_cursor = db_connection.cursor()
db_cursor.execute('select * from home_final')
table_rows = db_cursor.fetchall()
data = pd.read_sql('select * from home_final', con=db_connection)
df = pd.DataFrame(data)
df.head()

TARGET  Gender  Credit_amount  Education  Martial_status  Age
0       1       1         406597          4               1   25
1       0       0        1293502          2               3   45
2       0       1         135000          4               1   52
3       0       0         312682          4               2   52
4       0       1         513000          4               1   54

In [ ]:
# define X and y
feature_cols = ['Age','Gender','Education','Martial_status']
X = df[feature_cols]
y = df.TARGET

# train/test split
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

## Linear Support Vector Classifier (SVC)

In [ ]:
from sklearn.svm import SVC
SVC().fit(X, y).score(X, y)

In [ ]:
%pylab inline
import pylab as pl
import numpy as np

# Some nice default configuration for plots
pl.rcParams['figure.figsize'] = 10, 7.5
pl.rcParams['axes.grid'] = True
pl.gray()

In [ ]:
SVC()

This Study split the dataset into two random, non overlapping subsets:

In [ ]:
#split the dataset into two random, non overlapping subsets:
from sklearn.cross_validation import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=0) # random state can split like 1

print("train data shape: %r, train target shape: %r"
      % (X_train.shape, y_train.shape))
print("test data shape: %r, test target shape: %r"
      % (X_test.shape, y_test.shape))

- Whenever the **test** data score is **not as good as** the **train** score the model is **overfitting**

- Whenever the **train score is not close to 100%** accuracy the model is **underfitting**

This study retrain a new model on the first subset call the **training set**:

In [ ]:
svc = SVC(kernel='rbf').fit(X_train, y_train)
train_score = svc.score(X_train, y_train) 
train_score
print(' Performance of the model from the traning set',train_score*100)

Here this study compute the performance of the model on new, held out data from the **test set**:

In [ ]:
test_score = svc.score(X_test, y_test)
print(' Performance of the model from the test set',test_score*100)

This score is clearly a good as expected! The model generalize so well to new, unseen data.
- Whenever the **test** data score is **not as good as** the **train** score the model is **overfitting**

- Whenever the **train score is not close to 100%** accuracy the model is **underfitting**

Ideally **we want to neither overfit nor underfit**: `test_score ~= train_score ~= 1.0`. 

In [ ]:
svc

This study try again with another parameterization to observe any improvement:

In [ ]:
svc_2 = SVC(kernel='rbf', C=100, gamma=0.001).fit(X_train, y_train)
svc_2

In [ ]:
svc_2.score(X_train, y_train)

In [ ]:
svc_2.score(X_test, y_test)

In this case the model is almost perfectly able to generalize, at least according to our random train, test split.

### Introduction to  C and gamma 

C and Gamma are the parameters of a Gaussian radial basis function kernel non - linear support vector machine (SVM). A standard SVM aims at getting a margin between all positive and negative cases. Still, if some examples are wrong or extremely unusual, they may contribute to poor modelling. To this end, Cortes and Vapnik in 1995 proposed an idea of an SVM with a soft margin, which would enable some examples to be "ignored" or placed on the incorrect side of the border. C is the parameter for the soft cost margin function that controls the impact of each support vector and includes a stability penalty for dealing errors.

The gamma parameter defines how far a solo drill example, has influenced the body, with low values that mean ' far ' and high values that mean ' close. ' The gamma parameters can be regarded as the inverse of the influence range of samples selected as vectors of support by the parser.

## Resources
References:*From the video series: [Introduction to machine learning with scikit-learn](https://github.com/justmarkham/scikit-learn-videos)*
- German Credit Risk Analysis : Beginner's Guide: [ Beginner's Guide ](https://www.kaggle.com/pahulpreet/german-credit-risk-analysis-beginner-s-guide/notebook) 


- scikit-learn documentation: [Cross-validation](http://scikit-learn.org/stable/modules/cross_validation.html), [Model evaluation](http://scikit-learn.org/stable/modules/model_evaluation.html)
- scikit-learn issue on GitHub: [MSE is negative when returned by cross_val_score](https://github.com/scikit-learn/scikit-learn/issues/2439)
- Section 5.1 of [An Introduction to Statistical Learning](http://www-bcf.usc.edu/~gareth/ISL/) (11 pages) and related videos: [K-fold and leave-one-out cross-validation](https://www.youtube.com/watch?v=nZAM5OXrktY) (14 minutes), [Cross-validation the right and wrong ways](https://www.youtube.com/watch?v=S06JpVoNaA0) (10 minutes)
- Scott Fortmann-Roe: [Accurately Measuring Model Prediction Error](http://scott.fortmann-roe.com/docs/MeasuringError.html)
- Machine Learning Mastery: [An Introduction to Feature Selection](http://machinelearningmastery.com/an-introduction-to-feature-selection/)
- Harvard CS109: [Cross-Validation: The Right and Wrong Way](https://github.com/cs109/content/blob/master/lec_10_cross_val.ipynb)
- Journal of Cheminformatics: [Cross-validation pitfalls when selecting and assessing regression and classification models](http://www.jcheminf.com/content/pdf/1758-2946-6-10.pdf)